# Generated by Django 3.1 on 2021-02-27 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choreinstance',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='choreinstance',
            name='submission_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
